#include "cs_types.h"

//namespace cakeserver {

IntDict RESMSG = {
    { 200, "HTTP/1.1 200 OK\r\nContent-type, text/html\r\n\r\n" },
    { 404, "HTTP/1.1 404 Not Found\r\nContent-type, text/html\r\n\r\n" }
};

set<string> METHODS = {
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "HEAD"
};

IntDict STATUSCODE = {
    // Information 1XX
    { 100, "Continue" },
    { 101, "Switching Protocols" },
    // Successful 2XX
    { 200, "OK" },
    { 201, "Cleated" },
    { 202, "Acepted" },
    { 203, "Non-Authoritative Information" },
    { 204, "No Content" },
    { 205, "Reset Content" },
    { 206, "Partial Content" },
    // Redirection 3XX
    { 300, "Multiple Choices" },
    { 301, "Move Permanently" },
    { 302, "Found" },
    { 303, "See Other" },
    { 304, "Not Modified" },
    { 305, "Use Proxy" },
    // Client Error 4XX
    { 400, "Bad Request" },
    { 401, "Unauthorized" },
    { 402, "Payment Required" },
    { 404, "Not Found" },
    { 405, "Method Not Allowed" },
    { 406, "Not Acceptable" },
    { 407, "Proxy Authentication Required" },
    { 408, "Request Timeout" },
    { 409, "Conflict" },
    { 410, "Gone" },
    { 411, "Length Required" },
    { 412, "Precondition Failed" },
    { 413, "Request Entity Too Large" },
    { 414, "Request-URI Too Long" },
    { 415, "Unsupported Media Type" },
    { 416, "Requested Range Not Satisfiable" },
    { 417, "Expectation Failed" },
    // Server Error 5XX
    { 500, "Internal Server Error" },
    { 501, "Not Implemented" },
    { 502, "Bad Gateway" },
    { 503, "Service Unavailable" },
    { 504, "Gateway Timeout" },
    { 505, "HTTP Version Not Supported" }
};

StrDict MIMETYPE = {
    { "aiff", "audio/x-aiff" },
    { "arj", "application/x-arj-compressed" },
    { "asf", "video/x-ms-asf" },
    { "asx", "video/x-ms-asx" },
    { "au", "audio/ulaw" },
    { "avi", "video/x-msvideo" },
    { "bcpio", "application/x-bcpio" },
    { "ccad", "application/clariscad" },
    { "cod", "application/vnd.rim.cod" },
    { "com", "application/x-msdos-program" },
    { "cpio", "application/x-cpio" },
    { "cpt", "application/mac-compactpro" },
    { "csh", "application/x-csh" },
    { "css", "text/css" },
    { "deb", "application/x-debian-package" },
    { "dl", "video/dl" },
    { "doc", "application/msword" },
    { "drw", "application/drafting" },
    { "dvi", "application/x-dvi" },
    { "dwg", "application/acad" },
    { "dxf", "application/dxf" },
    { "dxr", "application/x-director" },
    { "etx", "text/x-setext" },
    { "ez", "application/andrew-inset" },
    { "fli", "video/x-fli" },
    { "flv", "video/x-flv" },
    { "gif", "image/gif" },
    { "gl", "video/gl" },
    { "gtar", "application/x-gtar" },
    { "gz", "application/x-gzip" },
    { "hdf", "application/x-hdf" },
    { "hqx", "application/mac-binhex40" },
    { "html", "text/html" },
    { "ice", "x-conference/x-cooltalk" },
    { "ief", "image/ief" },
    { "igs", "model/iges" },
    { "ips", "application/x-ipscript" },
    { "ipx", "application/x-ipix" },
    { "jad", "text/vnd.sun.j2me.app-descriptor" },
    { "jar", "application/java-archive" },
    { "jpeg", "image/jpeg" },
    { "jpg", "image/jpeg" },
    { "js", "text/javascript" },
    { "json", "application/json" },
    { "latex", "application/x-latex" },
    { "lsp", "application/x-lisp" },
    { "lzh", "application/octet-stream" },
    { "m", "text/plain" },
    { "m3u", "audio/x-mpegurl" },
    { "man", "application/x-troff-man" },
    { "me", "application/x-troff-me" },
    { "midi", "audio/midi" },
    { "mif", "application/x-mif" },
    { "mime", "www/mime" },
    { "movie", "video/x-sgi-movie" },
    { "mp3", "audio/mpeg" },
    { "mp4", "video/mp4" },
    { "mpg", "video/mpeg" },
    { "mpga", "audio/mpeg" },
    { "ms", "application/x-troff-ms" },
    { "mtl", "text/plain" },
    { "obj", "text/plain" },
    { "nc", "application/x-netcdf" },
    { "oda", "application/oda" },
    { "ogm", "application/ogg" },
    { "pbm", "image/x-portable-bitmap" },
    { "pdf", "application/pdf" },
    { "pgm", "image/x-portable-graymap" },
    { "pgn", "application/x-chess-pgn" },
    { "pgp", "application/pgp" },
    { "pm", "application/x-perl" },
    { "png", "image/png" },
    { "pnm", "image/x-portable-anymap" },
    { "ppm", "image/x-portable-pixmap" },
    { "ppz", "application/vnd.ms-powerpoint" },
    { "pre", "application/x-freelance" },
    { "prt", "application/pro_eng" },
    { "ps", "application/postscript" },
    { "qt", "video/quicktime" },
    { "ra", "audio/x-realaudio" },
    { "rar", "application/x-rar-compressed" },
    { "ras", "image/x-cmu-raster" },
    { "rgb", "image/x-rgb" },
    { "rm", "audio/x-pn-realaudio" },
    { "rpm", "audio/x-pn-realaudio-plugin" },
    { "rtf", "text/rtf" },
    { "rtx", "text/richtext" },
    { "scm", "application/x-lotusscreencam" },
    { "set", "application/set" },
    { "sgml", "text/sgml" },
    { "sh", "application/x-sh" },
    { "shar", "application/x-shar" },
    { "silo", "model/mesh" },
    { "sit", "application/x-stuffit" },
    { "skt", "application/x-koan" },
    { "smil", "application/smil" },
    { "snd", "audio/basic" },
    { "sol", "application/solids" },
    { "spl", "application/x-futuresplash" },
    { "src", "application/x-wais-source" },
    { "stl", "application/SLA" },
    { "stp", "application/STEP" },
    { "sv4cpio", "application/x-sv4cpio" },
    { "sv4crc", "application/x-sv4crc" },
    { "svg", "image/svg+xml" },
    { "swf", "application/x-shockwave-flash" },
    { "tar", "application/x-tar" },
    { "tcl", "application/x-tcl" },
    { "tex", "application/x-tex" },
    { "texinfo", "application/x-texinfo" },
    { "tgz", "application/x-tar-gz" },
    { "tiff", "image/tiff" },
    { "tr", "application/x-troff" },
    { "tsi", "audio/TSP-audio" },
    { "tsp", "application/dsptype" },
    { "tsv", "text/tab-separated-values" },
    { "txt", "text/plain" },
    { "unv", "application/i-deas" },
    { "ustar", "application/x-ustar" },
    { "vcd", "application/x-cdlink" },
    { "vda", "application/vda" },
    { "vivo", "video/vnd.vivo" },
    { "vrm", "x-world/x-vrml" },
    { "wav", "audio/x-wav" },
    { "wax", "audio/x-ms-wax" },
    { "wma", "audio/x-ms-wma" },
    { "wmv", "video/x-ms-wmv" },
    { "wmx", "video/x-ms-wmx" },
    { "wrl", "model/vrml" },
    { "wvx", "video/x-ms-wvx" },
    { "xbm", "image/x-xbitmap" },
    { "xlw", "application/vnd.ms-excel" },
    { "xml", "text/xml" },
    { "xpm", "image/x-xpixmap" },
    { "xwd", "image/x-xwindowdump" },
    { "xyz", "chemical/x-pdb" },
    { "zip", "application/zip" }
};

//}